
meta_name: "FrontRow"
meta_title: "FrontRow - For concert go-ers"
meta_description: "Concert go-ers who want to connect and share experiences with other fans, and who want to track the concerts they've seen."
meta_image: "cover.png"
